<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Miscellaneous language phrases


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'block_ip_button' => 'Blokiraj IP adresu',
	'browse_categories' => 'Listaj kategorije',
	'captcha_approve_fix' => 'Ova verifikacija više neće biti potrebna nakon što tvoj nalog bude aktivan.',
	'captcha_confirm_fix' => 'Ako te ova verifikacija nervira, molimo te da ^5potvrdiš svoju email adresu^6.',
	'captcha_error' => 'Potvrdi da nisi robot',
	'captcha_label' => 'Anti-spam verifikacija:',
	'captcha_login_fix' => 'Ako te ova verifikacija nervira ^1prijavi se^2 ili se ^3registruj^4.',
	'feed_a_edited_prefix' => 'Odgovor je izmenjen: ',
	'feed_a_prefix' => 'Odgovoreno: ',
	'feed_a_reshown_prefix' => 'Odgovor je ponovo prikazan: ',
	'feed_a_selected_prefix' => 'Izabran odgovor: ',
	'feed_c_edited_prefix' => 'Izmenjen komentar: ',
	'feed_c_moved_prefix' => 'Premešten komentar: ',
	'feed_c_prefix' => 'Komentarisan: ',
	'feed_c_reshown_prefix' => 'komentar ponovo prikazan: ',
	'feed_closed_prefix' => 'Zatvoreno: ',
	'feed_edited_prefix' => 'Izmenjeno: ',
	'feed_hidden_prefix' => 'Sakriveno: ',
	'feed_not_found' => 'Feed nije pronađen',
	'feed_recategorized_prefix' => 'Promenjena kategorija: ',
	'feed_reopened_prefix' => 'Ponovo otvoreno: ',
	'feed_reshown_prefix' => 'Ponovo prikazano: ',
	'feed_retagged_prefix' => 'Ponovo označeno: ',
	'feedback_email' => 'Tvoj email: (opciono)',
	'feedback_empty' => 'Unesi ovde tvoje komentar ili sugestije',
	'feedback_message' => 'Tvoji komentari i sugestije za ^:',
	'feedback_name' => 'Tvoje ime: (opciono)',
	'feedback_sent' => 'Tvoja poruka je poslata,  hvala.',
	'feedback_title' => 'Pošalji povratne informacije',
	'form_security_again' => 'Molimo te klikni ponovo radi potvrde',
	'form_security_reload' => 'Molimo te osveži stranicu pa pokušaj ponovo',
	'hide_all_ip_button' => 'Sakrij sve objave sa ove IP adrese',
	'host_name' => 'Ime hosta:',
	'inbox' => 'Prijemno sanduče',
	'matches_blocked_ips' => 'Podudarane blokirane IP adrese:',
	'message_empty' => 'Unesi poruku koju želiš da pošalješ ovom korisniku',
	'message_explanation' => 'Ovo će biti poslato kao obaveštenje od ^. Tvoja email adresa neće biti vidljiva, sem ukoliko je ne napišeš u poruci.',
	'message_for_x' => 'Tvoja poruka za ^:',
	'message_limit' => 'Ne možeš poslati više poruka u ovom satu.',
	'message_must_login' => 'Molimo te ^1prijavi se^2 ili se ^3registruj^4 ako želiš da pošalješ privatnu poruku.',
	'message_recent_history' => 'Skorašnja dopisivanja sa ^',
	'message_sent' => 'Tvoja privatna poruka je poslata',
	'more_favorite_qs' => 'Još omiljenih pitanja...',
	'more_favorite_tags' => 'Još omiljenih oznaka...',
	'more_favorite_users' => 'Još omiljenih korisnika...',
	'my_favorites_title' => 'Moji favoriti',
	'nav_all_my_updates' => 'Sva moja ažuriranja',
	'nav_my_content' => 'Moj sadržaj',
	'nav_my_details' => 'Moj nalog',
	'nav_my_favorites' => 'Moje omiljene stavke',
	'nav_user_activity' => 'Skorašnja aktivnost',
	'nav_user_as' => 'Svi odgovori',
	'nav_user_pms' => 'Privatne poruke',
	'nav_user_qs' => 'Sva pitanja',
	'nav_user_wall' => 'Zid',
	'next_step' => 'Sledeći korak',
	'no_activity_from_x' => 'Korisnik ^ nema aktivnosti',
	'no_favorite_categories' => 'Nema omiljenih kategorija',
	'no_favorite_qs' => 'Nema omiljenih pitanja',
	'no_favorite_tags' => 'Nema omiljenih oznaka',
	'no_favorite_users' => 'Nema omiljenih korisnika',
	'no_recent_updates' => 'Nema skorašnjih ažuriranja',
	'no_updates_content' => 'Nema skorašnjih ažuriranja za moj sadržaj',
	'no_updates_favorites' => 'Nema ažuriranja za omiljeni sadržaj',
	'outbox' => 'Poslato',
	'pm_inbox_title' => 'Primljene privatne poruke',
	'pm_outbox_title' => 'Poslate privatne poruke',
	'private_message_title' => 'Pošalji privatnu poruku',
	'recent_activity_from_x' => 'Skorašnja aktivnost od ^',
	'recent_updates_content' => 'Skorašnja ažuriranja od mog sadržaja',
	'recent_updates_favorites' => 'Skorašnja ažuriranja omiljenih',
	'recent_updates_title' => 'Skorašnja ažuriranja od mene',
	'site_in_maintenance' => 'Ovaj sajt je trenutno nedostupan zbog održavanja. Pokušajte kroz koji minut. Hvala.',
	'suggest_favorites_add' => 'Da dodaš pitanje ili nešto drugo u omiljene, klikni ^ na vrhu te stranice.',
	'suggest_update_favorites' => 'Ako želiš više novosti, dodaj stavke u ^1omiljene^2.',
	'unblock_ip_button' => 'Odblokiraj IP',
	'your_a_commented' => 'tvoj odgovor je komentarisan',
	'your_a_edited' => 'tvoj odgovor je izmenjen',
	'your_a_hidden' => 'tvoj odgovor je sakriven',
	'your_a_questioned' => 'postavio/la pitanje na tvoj odgovor',
	'your_a_reshown' => 'tvoj odgovor je ponovo prikazan',
	'your_a_selected' => 'tvoj odgovor je izabran',
	'your_c_edited' => 'tvoj komentar je izmenjen',
	'your_c_followed' => 'tvoj komentar je praćen',
	'your_c_hidden' => 'tvoj komentar je sakriven',
	'your_c_moved' => 'tvoj komentar je premešten',
	'your_c_reshown' => 'tvoj komentar je ponovo prikazan',
	'your_q_answered' => 'na tvoje pitanje je dodat odgovor',
	'your_q_closed' => 'tvoje pitanje je zatvoreno',
	'your_q_commented' => 'na tvoje pitanje je dodat komentar',
	'your_q_edited' => 'tvoje pitanje je izmenjeno',
	'your_q_hidden' => 'tvoje pitanje je sakriveno',
	'your_q_recategorized' => 'tvoje pitanje je promenilo kategoriju',
	'your_q_reopened' => 'tvoje pitanje je ponovo otvoreno',
	'your_q_reshown' => 'tvoje pitanje je ponovo prikazano',
	'your_q_retagged' => 'tvoje pitanje ima novu oznaku',
);
