<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for user management


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'about' => 'O',
	'add_user_x_favorites' => 'Dodaj korisnika ^ u moje omiljene',
	'approve_required' => 'Sačekaj da tvoj nalog bude odobren ili ^1dodaj više informacija^2.', // @deprecated
	'approve_title' => 'Čeka se na odobrenje korisnika',
	'approve_user_button' => 'Odobri korisnika',
	'approved_user' => 'Korisnik odobren',
	'avatar_default' => 'Podrazumevano',
	'avatar_gravatar' => 'Prikaži moj ^1Gravatar^2',
	'avatar_label' => 'Sličica naloga:',
	'avatar_none' => 'Nema',
	'block_user_button' => 'Blokiraj korisnika',
	'blocked_users' => 'Blokirani korisnici',
	'category_level_add' => ' - ^1dodaj privilegije na nivou kategorije^2',
	'category_level_in' => 'za sledeće kategorije:',
	'category_level_label' => 'Unapređen na:',
	'category_level_none' => 'Bez unapređenja',
	'change_email_link' => ' - ^1promeni email^2',
	'change_password' => 'Promeni lozinku',
	'confirm_button' => 'Potvrdi email adresu',
	'confirm_complete' => 'Hvala, tvoja email adresa je potvrđena.',
	'confirm_emailed' => 'Poslalismo ti link za potvrdi na email. Klikni na link iz porukeda potvrdiš email, ili unesi kod za potvrdu ispod.',
	'confirm_required' => 'Da bi završio/la registraciju, klikni na link koji ti je poslat na email, ili ^1zatraži novi link^2.',
	'confirm_title' => 'Potvrda email adrese',
	'confirm_wrong_log_in' => 'Kod nije ispravan - molimo ^1prijavi se^2 da bi poslao/la novi link',
	'confirm_wrong_resend' => 'Kod nije ispravan - klikni ispod da pošalješ novi',
	'delete_user_button' => 'Obriši korisnika',
	'edit_profile' => 'Izmeni moj profil',
	'edit_user_button' => 'Izmeni korisnika',
	'email_code_another' => 'pošalji novi',
	'email_code_emailed' => 'Kod za potvrdu je poslat',
	'email_code_label' => 'Kod:',
	'email_code_wrong' => 'Kod nije ispravan',
	'email_confirmed' => 'Potvrđeno',
	'email_exists' => 'Email adresa je već vezana za neki nalog',
	'email_handle_label' => 'Email ili korisničko ime:',
	'email_invalid' => 'Email nije ispravan - proveri pa pokušaj ponovo',
	'email_label' => 'Email:',
	'email_not_confirmed' => 'Još uvek nije potvrđen',
	'email_please_confirm' => 'Molimo te ^5potvrdi^6',
	'email_required' => 'Email adresa je obavezna (neće biti javna)',
	'forgot_link' => 'Zaboravio/la sam lozinku',
	'full_name' => 'Tvoje ime',
	'handle_blocked' => 'Ovo korisničko ime je zabranjeno, probaj neko drugo',
	'handle_empty' => 'Korisničko ime ne može biti prazno',
	'handle_exists' => 'Korisničko ime je zauzeto, probaj neko drugo',
	'handle_has_bad' => 'Korisničko ime ne sme da sadrži: ^',
	'handle_label' => 'Korisničko ime:',
	'hide_all_user_button' => 'Sakrij sve objave ovog korisnika',
	'last_login_label' => 'Poslednja prijava:',
	'last_write_label' => 'Poslednja pisana aktivnost:',
	'level_admin' => 'Administrator',
	'level_editor' => 'Urednik',
	'level_expert' => 'Ekspert',
	'level_for_category' => '^1 za ^2',
	'level_in_general' => 'generalno',
	'level_moderator' => 'Moderator',
	'level_super' => 'Super Administrator',
	'location' => 'Lokacija',
	'log_in_to_access' => 'Sada se možeš ^1prijaviti^2 da pristupiš svom nalogu.',
	'login_button' => 'Prijavi se',
	'login_limit' => 'Previše pokušaja prijave. Probaj ponovo kroz sat vremena',
	'login_title' => 'Prijava',
	'mass_mailings' => 'Masovni mejlovi:',
	'mass_mailings_explanation' => 'Prijavi se na email poruke koje se šalju svima',
	'member_for' => 'Korisnik već:',
	'member_type' => 'Tip:',
	'new_password_1' => 'Nova lozinka:',
	'new_password_2' => 'Ponovi novu lozinku:',
	'no_blocked_users' => 'Nema blokiranih korisnika',
	'no_permission' => 'Nemaš dozvolu da izvršiš ovu akciju',
	'old_password' => 'Stara lozinka:',
	'only_shown_admins' => '(vidite jedino ti i admin)',
	'only_shown_editors' => '(vidiš jedino ti, urednik i admin)',
	'only_shown_experts' => '(vidiš jedino ti, ekspert i admin)',
	'only_shown_moderators' => '(vidiš jedino ti, moderator i admin)',
	'password_changed' => 'Lozinka promenjena',
	'password_label' => 'Lozinka:',
	'password_min' => 'Lozinka mora sadržati makar ^ karaktera',
	'password_mismatch' => 'Nova lozinka se ne podudara',
	'password_none' => 'Da se prijaviš direktno, unesi lozinku ispod',
	'password_sent' => 'Tvoja nova lozinka ti je poslata na email.',
	'password_to_set' => 'Postavi na stranici svog naloga',
	'password_wrong' => 'Lozinka nije ispravna',
	'private_messages' => 'Privatne poruke:',
	'private_messages_explanation' => 'Dozvoli korisnicima da ti pišu (ne vide tvoju email adresu)',
	'profile_saved' => 'Profil sačuvan',
	'register_button' => 'Registruj se',
	'register_limit' => 'Previše registracija, probaj ponovo kroz sat vremena',
	'register_suspended' => 'Registracija novih korisnika je trenutno onemogućena, probaj ponovo malo kasnije.',
	'register_title' => 'Registruj se kao novi korisnik',
	'registered_label' => 'Registrovan:',
	'registered_user' => 'Registrovan korisnik',
	'remember' => 'Upamti me',
	'remember_label' => 'Upamti me na ovom računaru',
	'remove_avatar' => 'Ukloni profilnu sličicu:',
	'reset_title' => 'Resetuj zaboravljenu lozinku',
	'save_profile' => 'Sačuvaj profil',
	'save_user' => 'Sačuvaj korisnika',
	'send_confirm_button' => 'Pošalji link za potvrdu',
	'send_reset_button' => 'Pošalji email za resetovanje lozinke',
	'send_reset_note' => 'Poruka sa instrukcijama će biti poslata na tvoju email adresu.',
	'special_users' => 'Specijalni korisnici',
	'terms_not_accepted' => 'Moraš prihvatiti uslove.',
	'unblock_user_button' => 'Odblokiraj korisnika',
	'unsubscribe' => 'Odjavi se:',
	'unsubscribe_complete' => 'Odjavljen/a  si sa masovne mejling liste koje je poslao ^0. Možeš se ponovo prijaviti preko svog ^1naloga^2.',
	'unsubscribe_title' => 'Odjava sa liste',
	'unsubscribe_wrong_log_in' => 'Kod nije ispravan - ^1prijavi se^2 da bi se odjavio/la sa liste',
	'user_blocked' => '(blokiran)',
	'user_not_found' => 'Korisnik nije pronađen',
	'wall_posts' => 'Objave sa zida:',
	'wall_posts_explanation' => 'Dozvoli da drugi pišu na tvom zidu (dobićeš email obaveštenje o tome)',
	'website' => 'Sajt',
	'x_ago_from_y' => 'pre ^1 sa ^2',
);
