<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'_decimal_point' => '.',
	'_thousands_separator' => ',',
	'_thousands_suffix' => 'k',
	'_millions_suffix' => 'm',
	'1_answer' => '1 odgovor',
	'1_comment' => '1 komentar',
	'1_day' => '1 dan',
	'1_disliked' => '1 dislajk',
	'1_flag' => '1 upozorenje',
	'1_hour' => '1 sat',
	'1_liked' => '1 lajk',
	'1_minute' => '1 minut',
	'1_month' => '1 mesec',
	'1_point' => '1 poen',
	'1_question' => '1 pitanje',
	'1_second' => '1 sekund',
	'1_tag' => '1 oznaka',
	'1_user' => '1 korisnik',
	'1_view' => '1 pregled',
	'1_vote' => '1 glas',
	'1_week' => '1 nedelja',
	'1_year' => '1 godina',
	'add_category_x_favorites' => 'Dodaj kategoriju ^ u omiljene',
	'add_favorites' => 'Dodaj u omiljene',
	'add_tag_x_favorites' => 'Dodaj oznaku ^ u omiljene',
	'all_categories' => 'Sve kategorije',
	'anonymous' => 'anonimni',
	'answer_edited' => 'odgovor je izmenjen',
	'answer_reshown' => 'odgovor je ponovo prikazan',
	'answer_selected' => 'izabran odgovor',
	'answered' => 'odgovorio',
	'answered_qs_in_x' => 'Pitanje sa najviše odgovora u ^',
	'answered_qs_title' => 'Pitanja sa najviše odgovora',
	'asked' => 'pitao/la',
	'asked_related_q' => 'slična pitanja',
	'by_x' => 'korisnik ^',
	'cancel_button' => 'Otkaži',
	'closed' => 'zatvoreno',
	'comment_edited' => 'komentar je izmenjen',
	'comment_moved' => 'komentar je premešten',
	'comment_reshown' => 'komentar je ponovo prikazan',
	'commented' => 'komentarisao',
	'date_day_min_digits' => 1, // 1 or 2
	'date_format_other_years' => '^day, ^month, ^year',
	'date_format_this_year' => '^day. ^month',
	'date_month_1' => 'Jan',
	'date_month_2' => 'Feb',
	'date_month_3' => 'Mar',
	'date_month_4' => 'Apr',
	'date_month_5' => 'Maj',
	'date_month_6' => 'Jun',
	'date_month_7' => 'Jul',
	'date_month_8' => 'Avg',
	'date_month_9' => 'Sep',
	'date_month_10' => 'Okt',
	'date_month_11' => 'Nov',
	'date_month_12' => 'Dec',
	'date_year_digits' => 4, // 2 or 4
	'edited' => 'izmenjeno',
	'email_error' => 'Desila se greška prilikom slanja mail-a.',
	'field_required' => 'Unesi nešto u ovo polje',
	'file_upload_limit_exceeded' => 'Fajl je prevelik',
	'general_error' => 'Desila se nepoznata greška, probaj ponovo',
	'hidden' => 'skriveno',
	'highest_users' => 'Korisnici sa najviše poena',
	'hot_qs_in_x' => 'Popularna pitanja u ^',
	'hot_qs_title' => 'Popularna pitanja',
	'image_not_read' => 'Format slike nije podržan, probaj sa: ^',
	'image_too_big_x_pc' => 'Slika je prevelika, smanji je na ^% pa probaj ponovo.',
	'in_category_x' => 'u ^',
	'ip_address_x' => 'IP adresa ^',
	'logged_in_x' => 'Ćao ^',
	'max_length_x' => 'Maksimalna dužina je ^ karaktera',
	'max_upload_size_x' => 'Maksimalna veličina fajla je ^',
	'me' => 'ja',
	'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
	'min_length_x' => 'Dodaj još informacija, makar ^ karaktera',
	'moved' => 'premešteno',
	'nav_activity' => 'Sve aktivnosti',
	'nav_admin' => 'Admin',
	'nav_ask' => 'Postavi pitanje',
	'nav_categories' => 'Kategorije',
	'nav_feedback' => 'Povratne informacije',
	'nav_home' => 'Početna',
	'nav_hot' => 'Popularno!',
	'nav_login' => 'Prijava',
	'nav_logout' => 'Odjava',
	'nav_most_answers' => 'Najviše odgovora',
	'nav_most_recent' => 'Skorašnje',
	'nav_most_views' => 'Najviše pregleda',
	'nav_most_votes' => 'Najviše glasova',
	'nav_no_answer' => 'Bez odgovora',
	'nav_no_selected_answer' => 'Bez označenog odgovora',
	'nav_no_upvoted_answer' => 'Bez pozitivnih glasova',
	'nav_qa' => 'Q&A',
	'nav_qs' => 'Pitanja',
	'nav_register' => 'Registruj se',
	'nav_tags' => 'Oznake',
	'nav_unanswered' => 'Bez odgovora',
	'nav_updates' => 'Moje novosti',
	'nav_users' => 'Korisnici',
	'newest_users' => 'Novi korisnici',
	'no_active_users' => 'Nema aktivnih korisnika trenutno',
	'no_answers_found' => 'Odgovori nisu pornađeni',
	'no_answers_in_x' => 'Nema odgovora u ^',
	'no_categories_found' => 'Nema pronađenih kategorija',
	'no_category' => 'Nema karaktere',
	'no_comments_found' => 'Komentari nisu pronađeni',
	'no_comments_in_x' => 'Nema komentara u ^',
	'no_questions_found' => 'Pitanja nisu pronađena',
	'no_questions_in_x' => 'Nema pitanja u ^',
	'no_related_qs_title' => 'Nema sličnih pitanja',
	'no_results_for_x' => 'Nema rezultata za ^',
	'no_tags_found' => 'Oznake nisu pronađene',
	'no_una_questions_found' => 'Nema pitanja bez odgovora',
	'no_una_questions_in_x' => 'Nema pitanja bez odgovora u ^',
	'no_unselected_qs_found' => 'Nema pitanja bez izabranog odgovora',
	'no_unupvoteda_qs_found' => 'Nema pitanja bez pozitivnih ocena',
	'page_label' => 'Strana:',
	'page_next' => 'dalje',
	'page_not_found' => 'Stranica nije pronađena',
	'page_prev' => 'nazad',
	'popular_tags' => 'Najpopularnije oznake',
	'questions_tagged_x' => 'Najnovija pitanja sa oznakom ^',
	'recategorized' => 'rekategorizovano',
	'recent_activity_in_x' => 'Skorašnja aktivnost u ^',
	'recent_activity_title' => 'Skorašnja aktivnost',
	'recent_as_in_x' => 'Najnovija pitanja sa odgovorima u ^',
	'recent_as_title' => 'Najnovija pitanja sa odgovorima',
	'recent_cs_in_x' => 'Najnoviji komentari na pitanja u ^',
	'recent_cs_title' => 'Najnoviji komentari na pitanja',
	'recent_qs_as_in_x' => 'Najnovija pitanja i odgovori u "^"',
	'recent_qs_as_title' => 'Najnovija pitanja i odgovori',
	'recent_qs_in_x' => 'Najnovija pitanja u ^',
	'recent_qs_title' => 'Najnovija pitanja',
	'related_qs_title' => 'Slična pitanja',
	'remove_favorites' => 'Ukloni iz omiljnih',
	'remove_x_favorites' => 'Ukloni ^ iz omiljnih',
	'reopened' => 'ponovo otvorio',
	'reshown' => 'ponovo prikazao',
	'results_for_x' => 'Rezultati pretrage za ^',
	'retagged' => 'ponovo označeno',
	'save_button' => 'Sačuvaj izmene',
	'search_button' => 'Pretraži',
	'search_explanation' => 'Unesi nekoliko reči za pretragu pa probaj ponovo.',
	'search_title' => 'Rezultati pretrage',
	'selected' => 'izabrao',
	'send_button' => 'Pošalji',
	'since_x' => 'od ^',
	'suggest_ask' => 'To je sve za sada. ^1Postavi novo pitanje^2.',
	'suggest_category_qs' => 'Da vidiš više, idi na ^1sva pitanja iz ove kategorije^2.',
	'suggest_qs' => 'Da vidiš više, idi na ^1celu listu pitanja^2.',
	'suggest_qs_tags' => 'Da vidiš više, idi na celu listu ^1pitanja^2 ili ^3popularnih oznaka^4.',
	'to_x' => 'u ^',
	'unanswered_qs_in_x' => 'Pitanja bez odgovora u ^',
	'unanswered_qs_title' => 'Najnovija pitanja bez odgovora',
	'unselected_qs_in_x' => 'Pitanja bez odabranog odgovora u ^',
	'unselected_qs_title' => 'Najnovija pitanja bez izabranog odgovora',
	'unupvoteda_qs_in_x' => 'Pitanja bez odgovora sa pozitivnim glasom u ^',
	'unupvoteda_qs_title' => 'Najnovija pitanja bez odgovora sa pozitivnim glasom',
	'upload_limit' => 'Previše zahteva. Probaj ponovo za sat vremena.',
	'view_q_must_be_approved' => 'Tvoj nalog mora biti odobren da bi video/la stranicu sa pitanjem. Sačekaj ili ^1dodaj više informacija^2.',
	'view_q_must_confirm' => 'Molimo te ^5potvrdi svoju email adresu^6 da vidiš stranicu sa pitanjem.',
	'view_q_must_login' => 'Molimo te ^1prijavi se^2 ili se ^3registruj^4 da vidiš stranicu sa pitanjem.',
	'viewed_qs_in_x' => 'Pitanja sa najviše pregleda u ^',
	'viewed_qs_title' => 'Pitanja sa najviše pregleda',
	'vote_disabled_approve' => 'Tvoj nalog mora biti odobren pre nego što daš glas.',
	'vote_disabled_down' => 'Davanje negativnih ocena je dostupno samo nekim korisnicima.',
	'vote_disabled_down_approve' => 'Tvoj nalog mora biti odobren pre nego što daš negativan glas.',
	'vote_disabled_hidden_post' => 'Ne možeš glasati za skrivene objave.',
	'vote_disabled_hidden_a' => 'Ne možeš glasati za skrivene odgovore',  // @deprecated
	'vote_disabled_hidden_q' => 'Ne možeš glasati za skrivena pitanja',  // @deprecated
	'vote_disabled_level' => 'Glasanje je omogućeno samo određenim korisnicima',
	'vote_disabled_my_post' => 'Ne možeš dati glas svojoj objavi',
	'vote_disabled_my_a' => 'Ne možeš dati glas svom odgovoru',  // @deprecated
	'vote_disabled_my_q' => 'Ne možeš dati glas svom pitanju',  // @deprecated
	'vote_disabled_q_page_only' => 'Otvori ovo pitanje da bi glasao/la',
	'vote_disabled_queued' => 'Možeš dati glas samo odobrenim objavama',
	'vote_down_must_confirm' => 'Molimo te ^5potvrdi svoju email adresu^6 da bi glasao/la.',
	'vote_down_popup' => 'Klikni da daš negativan glas',
	'vote_limit' => 'Limit za glasanje je dosegnut. Pokušaj kasnije.',
	'vote_must_confirm' => 'Molimo te ^5potvrdi svoju email adresu^6 da bi glasao/la.',
	'vote_must_login' => 'Molimo te ^1prijavi se^2 ili se ^3registruj^4 da bi glasao/la.',
	'vote_not_allowed' => 'Za ovo glasanje nije dozvoljeno',
	'vote_up_popup' => 'klikni da daš pozitivan glas',
	'voted_down_popup' => 'Glasao/la si negativno - klikni da ukloniš',
	'voted_qs_in_x' => 'Pitanja sa najviše glasova u ^',
	'voted_qs_title' => 'Pitanja sa najviše glasova',
	'voted_up_popup' => 'Glasao/la si pozitivno - klikni da ukloniš',
	'written' => '', // blank in English - placeholder for other languages
	'x_ago' => 'pre ^',
	'x_answers' => '^ odgovora',
	'x_comments' => '^ komentara',
	'x_days' => '^ dana',
	'x_disliked' => '^ dislajkova',
	'x_flags' => '^ upozorenja',
	'x_hours' => '^ sati',
	'x_liked' => '^ lajkova',
	'x_minutes' => '^ minuta',
	'x_months' => '^ meseci',
	'x_points' => '^ poena',
	'x_questions' => '^ pitanja',
	'x_seconds' => '^ sekundi',
	'x_tags' => '^ oznaka',
	'x_users' => '^ korisnika',
	'x_views' => '^ pregleda',
	'x_votes' => '^ glasova',
	'x_weeks' => '^ nedelja',
	'x_years' => '^ godina',
);
