<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
	'1_answer_title' => '1 Odgovor',
	'a_convert_to_c' => 'Pretvori ovaj odgovor u komentar',
	'a_convert_to_c_on' => 'Pretvori ovaj odgovor u komentar na:',
	'a_convert_warn' => 'Upozorenje: ova konverzacija ne može biti vraćenja.',
	'a_convert_warn_cs' => 'Upozorenje: ova konverzacija ne može biti vraćenja  i takođe će biti premešteni komentari ovog pitanja.',
	'a_notify_email' => 'Pošalji mi poruku na ovaj email ako je moj odgovor izabran ili je dobio komentar:',
	'a_notify_label' => 'Pošalji mi email ako je moj odgovor izabran ili je dobio komentar',
	'a_notify_x_label' => 'Obavesti me na email (^) ako je moj odgovor izabran ili je dobio komentar',
	'a_waiting_your_approval' => 'Ovaj odgovor čeka na tvoje odobrenje',
	'a_your_waiting_approval' => 'Tvoj odgovor će biti proveren i odobren uskoro.',
	'add_answer_button' => 'Dodaj odgovor',
	'add_comment_button' => 'Dodaj komentar',
	'add_q_favorites' => 'Dodaj ovo pitanje u moje omiljene',
	'anon_name_label' => 'Tvoje ime za prikaz (opciono):',
	'answer_button' => 'Odgovori',
	'answer_limit' => 'Previše odgovora, probaj kroz sat vremena',
	'answer_must_be_approved' => 'Tvoj nalog mora biti odobren pre postavljanja pitanja. Molimo te sačekaj ili ^1dodaj više informacija^2.',
	'answer_must_confirm' => 'Molimo te ^5potvrdi svoju email adresu^6 da bi odgovrio/la na ovo pitanje.',
	'answer_must_login' => 'Molimo te ^1prijavi se^2 ili se ^3registruj^4 da bi odgovrio/la na ovo pitanje.',
	'answer_q_popup' => 'Odgovori na ovo pitanje',
	'approve_a_popup' => 'Odobri ovaj odgovor',
	'approve_button' => 'odobri',
	'approve_c_popup' => 'Odobri ovaj komentar',
	'approve_q_popup' => 'Odobri ovo pitanje',
	'ask_button' => 'Postavi pitanje',
	'ask_follow_from_a' => 'Tvoje pitanje je u vezi sa ovim odogovorom:',
	'ask_follow_title' => 'Postavi povezano pitanje',
	'ask_limit' => 'Previše pitanja, probaj kroz sat vremena',
	'ask_must_be_approved' => 'Tvoj nalog mora biti odobren pre postavljanja pitanja. Molimo sačekaj ili ^1dodaj više informacija^2.',
	'ask_must_confirm' => 'Molimo te da ^5potvrdiš email adresu^6 ako želiš da postaviš pitanje.',
	'ask_must_login' => 'Molimo te ^1prijavi se^2 ili se ^3registruj^4 ako želiš da postaviš pitanje.',
	'ask_same_q' => 'Pre nego što nastaviš, proveri da li odgovor na tvoje pitanje već postoji:',
	'ask_title' => 'Postavi pitanje',
	'c_notify_email' => 'Obavesti me na ovu email adresu ako neko ostavi komentar nakon mene:',
	'c_notify_label' => 'Obavesti me ako je neko ostavio komentar nakon mene',
	'c_notify_x_label' => 'Obavesti me na email (^) ako neko ostavi komentar nakon mene',
	'c_waiting_your_approval' => 'Ovaj komentar čeka na tvoje odobrenje',
	'c_your_waiting_approval' => 'Tvoj komentar će biti proveren i odobren uskoro.',
	'category_ask_not_allowed' => 'Nemaš dozvolu da postavljaš pitanja u ovoj kategoriji',
	'category_js_note' => 'Da bi izabrao/la kategoriju, molimo te da omogućiš Javascript u svom veb pregledaču.',
	'category_required' => 'Izaberi kategoriju',
	'claim_a_popup' => 'Dodeli ovaj odgovor svom korisničkom nalogu',
	'claim_button' => 'Ja sam napisao/la ovo',
	'claim_c_popup' => 'Dodeli ovaj komentar svom korisničkom nalogu',
	'claim_q_popup' => 'Dodeli ovo pitanjer svom korisničkom nalogu',
	'clear_flags_button' => 'izbriši upozorenja',
	'clear_flags_popup' => 'Izbriši svima upozorenja',
	'close_button' => 'zatvori',
	'close_duplicate' => 'Ovo je duplikat drugog pitanja',
	'close_duplicate_error' => 'Duplikat odgovora ne može biti pronađen - probaj da dodaš broj od duplikatskog pitanja, recimo: 123.',
	'close_form_button' => 'Zatvori pitanje',
	'close_form_title' => 'Zatvori ovo pitanje',
	'close_original_note' => 'Takođe možeš uneti broj pitanja koji se nalazi u linku, recimo: 123.',
	'close_original_title' => 'Link originalnog pitanja:',
	'close_q_popup' => 'Onemogući dodavanje odgovora od ovog trenutka',
	'close_reason_title' => 'Razlozi za zatvaranje pitanja, ili link do dupliranog pitanja:',
	'closed_as_duplicate' => 'zatvori jer je duplikat ovog pitanja:',
	'closed_with_note' => 'Zatvoreno zbog:',
	'comment_a_popup' => 'Dodaj komentar na ovo',
	'comment_button' => 'Dodaj komentar',
	'comment_limit' => 'Previše komentara je primljeno, pokušaj kroz sat vremena.',
	'comment_must_be_approved' => 'Moraš imati odobren nalog ako želiš da ostaviš komentar. Molimo sačekaj ili ^1dodaj više informacija^2.',
	'comment_must_confirm' => 'Molimo te da ^5potvrdiš svoj email^6 ako želiš da komentarišeš.',
	'comment_must_login' => 'Molimo te da se ^1prijaviš^2 ili se ^3registruješ^4 ako želiš da komentarišeš.',
	'comment_on_a' => 'Na odgovor: ',
	'comment_on_q' => 'Na pitanje: ',
	'comment_q_popup' => 'Dodaj komentar na ovo pitanje',
	'delete_a_popup' => 'Obriši ovaj odgovor zauvek',
	'delete_button' => 'obriši',
	'delete_c_popup' => 'Obriši ovaj komentar zauvek',
	'delete_q_popup' => 'Obriši ovo pitanje zauvek',
	'duplicate_content' => 'Tvoj unos je duplikat.',
	'edit_a_popup' => 'Izmeni ovaj odgovor',
	'edit_a_title' => 'Izmeni odgovor',
	'edit_button' => 'izmeni',
	'edit_c_popup' => 'Izmeni ovaj komentar',
	'edit_c_title' => 'Izmeni komentar',
	'edit_must_confirm' => 'Molimo te ^5potvrdi svoj email^6 ako želiš da ovo izmeniš.',
	'edit_must_login' => 'Molimo te da se ^1prijaviš^2 ili se ^3registruješ^4 ako želiš da ovo izmeniš.',
	'edit_q_popup' => 'Izmeni ovo pitanje',
	'edit_q_title' => 'Izmeni pitanje',
	'example_tags' => 'Primeri oznaka: ',
	'flag_a_popup' => 'Prijavi ovaj odgovor kao spam ili neprikladan',
	'flag_button' => 'prijavi',
	'flag_c_popup' => 'Prijavi ovaj komentar kao spam ili neprikladan',
	'flag_hide_button' => 'prijavi i sakrij',
	'flag_limit' => 'Previše prijavljenih objava, pokušak kroz sat vremena',
	'flag_must_confirm' => 'Molimo te ^5potvrdi svoj email^6 ako želiš da prijaviš ovo.',
	'flag_must_login' => 'Molimo te ^1prijavi se^2 ili se ^3registruj^4 ako želiš da prijaviš ovo.',
	'flag_not_allowed' => 'Nije moguće prijaviti ovo',
	'flag_q_popup' => 'Prijavi ovo pitanje kao spam ili neprikladno',
	'follow_a_popup' => 'Postavi novo pitanje u vezi sa ovim odgovorom',
	'follow_button' => 'postavi povezano pitanje',
	'follows_a' => 'U vezi sa ovim odgovorom:',
	'follows_q' => 'o ovom pitanju:',
	'hide_a_popup' => 'Sakrij ovaj odgovor',
	'hide_button' => 'sakrij',
	'hide_c_popup' => 'Sakrij ovaj komentar',
	'hide_q_popup' => 'Sakrij ovo pitanje',
	'matching_tags' => 'Oznake koje se podudaraju: ',
	'max_tags_x' => 'Maksimalno možeš dodati ^ oznaka',
	'min_tags_x' => 'Molimo te dodaj makar ^ oznaku/e',
	'notify_email_note' => 'Privatnost: tvoj email će biti korišten isključivo za slanje ovih obaveštenja.',
	'q_category_label' => 'Kategorija:',
	'q_content_label' => 'Više informacija o ovom pitanju:',
	'q_hidden_author' => 'Ovo pitanje je sakriveno od strane autora',
	'q_hidden_flagged' => 'Ovo pitanje je prijavljeno ili sakriveno',
	'q_hidden_other' => 'Ovo pitanje je sakriveno',
	'q_notify_email' => 'Pošalji mi poruku na ovu email adresu ako neko odgovori na moje pitanje ili doda komentar:',
	'q_notify_label' => 'Obavesti me na email ako neko odgovori na moje pitanje ili doda komentar',
	'q_notify_x_label' => 'Obavesti me na email (^) ako neko odgovori na moje pitanje ili doda komentar',
	'q_tags_comma_label' => 'Oznake - koristi zarez (,) za razdvajanje:',
	'q_tags_label' => 'Oznake - koristi crtice (-) da spojiš reči:',
	'q_title_label' => 'Pitanje u jednoj rečenici:',
	'q_waiting_approval' => 'Ovo pitanje čeka na odobrenje',
	'q_waiting_your_approval' => 'Ovo pitanje čeka na tvoje odobrenje',
	'q_your_waiting_approval' => 'Tvoje pitanje će biti provereno i odobreno uskoro.',
	'recat_button' => 'promeni',
	'recat_popup' => 'Promeni kategoriju ovog pitanja',
	'recat_q_title' => 'Promeni kategoriju',
	'reject_a_popup' => 'Odbaci ovaj odgovor',
	'reject_button' => 'odbaci',
	'reject_c_popup' => 'Odbaci ovaj komentar',
	'reject_q_popup' => 'Odbaci ovo pitanje',
	'remove_q_favorites' => 'Ukloni ovo pitanje iz liste omiljenih',
	'reopen_button' => 'ponovo otvori',
	'reopen_q_popup' => 'Ponovo otvori ovo pitanje',
	'reply_button' => 'odgovori',
	'reply_c_popup' => 'Odgovori na ovaj komentar',
	'reshow_a_popup' => 'Ponovo prikaži ovaj odgovor',
	'reshow_button' => 'prikaži',
	'reshow_c_popup' => 'Ponovo prikaži ovaj komentar',
	'reshow_q_popup' => 'Ponovo prikaži ovo pitanje',
	'retag_button' => 'ponovo označi',
	'retag_cat_popup' => 'Promeni kategoriju ili oznaku ovom pitanju',
	'retag_popup' => 'Promeni oznaku ovom pitanju',
	'retag_q_title' => 'Promeni oznaku pitanju',
	'save_silent_label' => 'Sačuvaj da niko ne zna da je izmenjeno',
	'select_popup' => 'Klikni da izabereš ovaj odgovor kao najbolji',
	'select_text' => 'Najbolji odgovor',
	'show_1_comment' => 'Prikaži 1 komentar',
	'show_1_previous_comment' => 'Prikaži 1 prethodni komnentar',
	'show_x_comments' => 'Prikaži ^ komentara',
	'show_x_previous_comments' => 'Prikaži ^ prethodnih komnentara',
	'unflag_button' => 'otkaži prijavu',
	'unflag_popup' => 'Ukloni prijavi koju si dodao/la',
	'unselect_popup' => 'Klikni da ukloniš izabrano',
	'x_answers_title' => '^ Odgovora',
	'your_answer_title' => 'Tvoj odgovor',
	'your_comment_a' => 'Tvoj komentar na ovaj odgovor:',
	'your_comment_q' => 'Tvoj komentar na ovo pitanje:',
);
